Import

In [ ]:
import pandas as pd;
print('Pandas Version:', pd.__version__)

Pandas Version: 2.2.3

In [ ]:
#Set of Name and Age
names = ['Abhay', 'Rohit', 'Sumit', 'Aditya', 'Rahul']
age = [22, 24, 20, 23, 25]

In [ ]:
data_set = list(zip(names, age))
data_set

[('Abhay', 22), ('Rohit', 24), ('Sumit', 20), ('Aditya', 23), ('Rahul', 25)]

In [ ]:
#Create the Data frame for this
df = pd.DataFrame(data = data_set, columns=['Names', 'Age'])
df

    Names  Age
0   Abhay   22
1   Rohit   24
2   Sumit   20
3  Aditya   23
4   Rahul   25

In [ ]:
df.shape

(5, 2)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Names   5 non-null      object
 1   Age     5 non-null      int64
dtypes: int64(1), object(1)
memory usage: 212.0+ bytes

In [ ]:
df.describe()

             Age
count   5.000000
mean   22.800000
std     1.923538
min    20.000000
25%    22.000000
50%    23.000000
75%    24.000000
max    25.000000

In [ ]:
weigths = [82, 78, 70, 91, 95]
df['Weigth'] = weigths
df

    Names  Age  Weigth
0   Abhay   22      82
1   Rohit   24      78
2   Sumit   20      70
3  Aditya   23      91
4   Rahul   25      95